import type { BrandName } from '../../models/types';

export interface SeedWrestler {
  name: string;
  avatar?: string;
  image?: string;
  gender: 'Male' | 'Female';
  alignment: 'Face' | 'Heel' | 'Tweener';
  faction?: string;
  rating: number;
  wins: number;
  losses: number;
  draws: number;
  injuryStatus: string;
  moral: number;
  contract: string;
  brandName: BrandName;
  holdsTitleNames?: string[];
}

export const WRESTLERS_SEED: SeedWrestler[] = [
  {
    name: 'AJ Styles',
    avatar: './visuals/Wrestlers/men/ajstyles/ajstylesavatar.png',
    image: './visuals/Wrestlers/men/ajstyles/ajstylesfull.png',
    gender: 'Male',
    alignment: 'Face',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'RAW',
    holdsTitleNames: []
  },
  {
    name: 'Akam',
    avatar: './visuals/Wrestlers/men/akam/akamavatar.png',
    image: './visuals/Wrestlers/men/akam/akamfull.png',
    gender: 'Male',
    alignment: 'Heel',
    faction: 'Authors Of Pain',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'RAW',
    holdsTitleNames: ['']
  },
  {
    name: 'Akira Tozawa',
    avatar: './visuals/Wrestlers/men/akiratozawa/akiratozawaavatar.png',
    image: './visuals/Wrestlers/men/akiratozawa/akiratozawafull.png',
    gender: 'Male',
    alignment: 'Face',
    faction: 'Alpha Academy',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'RAW',
    holdsTitleNames: ['']
  },
  {
    name: 'Andrade',
    avatar: './visuals/Wrestlers/men/andrade/andradeavatar.png',
    image: './visuals/Wrestlers/men/andrade/andradefull.png',
    gender: 'Male',
    alignment: 'Heel',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'NXT',
    holdsTitleNames: ['']
  },
  {
    name: 'Andre Chase',
    avatar: './visuals/Wrestlers/men/andrechase/andrechaseavatar.png',
    image: './visuals/Wrestlers/men/andrechase/andrechasefull.png',
    gender: 'Male',
    alignment: 'Face',
    faction: 'Chase University',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'NXT',
    holdsTitleNames: ['']
  },
  {
    name: 'Angel',
    avatar: './visuals/Wrestlers/men/angel/angelavatar.png',
    image: './visuals/Wrestlers/men/angel/angelfull.png',
    gender: 'Male',
    alignment: 'Heel',
    faction: 'Los Garza',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'NXT',
    holdsTitleNames: ['']
  },
  {
    name: 'Angelo Dawkins',
    avatar: './visuals/Wrestlers/men/angelodawkins/angelodawkinsavatar.png',
    image: './visuals/Wrestlers/men/angelodawkins/angelodawkinsfull.png',
    gender: 'Male',
    alignment: 'Face',
    faction: 'Street Profits',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'SMACKDOWN',
    holdsTitleNames: ['']
  },
  {
    name: 'Apollo Crews',
    avatar: './visuals/Wrestlers/men/apollocrews/apollocrewsavatar.png',
    image: './visuals/Wrestlers/men/apollocrews/apollocrewsfull.png',
    gender: 'Male',
    alignment: 'Face',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'SMACKDOWN',
    holdsTitleNames: ['']
  },
  {
    name: 'Ashante Adonis',
    avatar: './visuals/Wrestlers/men/ashantetheeadonis/ashantetheeadonisavatar.png',
    image: './visuals/Wrestlers/men/ashantetheeadonis/ashantetheeadonisfull.png',
    gender: 'Male',
    alignment: 'Heel',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'NXT',
    holdsTitleNames: ['']
  },
  {
    name: 'Austin Theory',
    avatar: './visuals/Wrestlers/men/austintheory/austintheoryavatar.png',
    image: './visuals/Wrestlers/men/austintheory/austintheoryfull.png',
    gender: 'Male',
    alignment: 'Heel',
    faction: 'The Vision',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'SMACKDOWN',
    holdsTitleNames: ['']
  },
  {
    name: 'Axiom',
    avatar: './visuals/Wrestlers/men/axiom/axiomavatar.png',
    image: './visuals/Wrestlers/men/axiom/axiomfull.png',
    gender: 'Male',
    alignment: 'Face',
    faction: 'Fraxiom',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'SMACKDOWN',
    holdsTitleNames: ['']
  },
  {
    name: 'Baron Corbin',
    avatar: './visuals/Wrestlers/men/baroncorbin/baroncorbinavatar.png',
    image: './visuals/Wrestlers/men/baroncorbin/baroncorbinfull.png',
    gender: 'Male',
    alignment: 'Heel',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'SMACKDOWN',
    holdsTitleNames: ['']
  },
  {
    name: 'Berto',
    avatar: './visuals/Wrestlers/men/berto/bertoavatar.png',
    image: './visuals/Wrestlers/men/berto/bertofull.png',
    gender: 'Male',
    alignment: 'Heel',
    faction: 'Los Garza',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'NXT',
    holdsTitleNames: ['']
  },
  {
    name: 'Braun Strowman',
    avatar: './visuals/Wrestlers/men/braunstrowman/braunstrowmanavatar.png',
    image: './visuals/Wrestlers/men/braunstrowman/braunstrowmanfull.png',
    gender: 'Male',
    alignment: 'Heel',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'RAW',
    holdsTitleNames: ['']
  },
  {
    name: 'Bron Breakker',
    avatar: './visuals/Wrestlers/men/bronbreakker/bronbreakkeravatar.png',
    image: './visuals/Wrestlers/men/bronbreakker/bronbreakkerfull.png',
    gender: 'Male',
    alignment: 'Heel',
    faction: 'The Vision',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'SMACKDOWN',
    holdsTitleNames: ['']
  },
  {
    name: 'Bronson Reed',
    avatar: './visuals/Wrestlers/men/bronsonreed/bronsonreedavatar.png',
    image: './visuals/Wrestlers/men/bronsonreed/bronsonreedfull.png',
    gender: 'Male',
    alignment: 'Heel',
    faction: 'The Vision',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'SMACKDOWN',
    holdsTitleNames: ['']
  },
  {
    name: 'Brooks Jensen',
    avatar: './visuals/Wrestlers/men/brooksjensen/brooksjensenavatar.png',
    image: './visuals/Wrestlers/men/brooksjensen/brooksjensenfull.png',
    gender: 'Male',
    alignment: 'Heel',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'NXT',
    holdsTitleNames: ['']
  },
  {
    name: 'Brutus Creed',
    avatar: './visuals/Wrestlers/men/brutuscreed/brutuscreedavatar.png',
    image: './visuals/Wrestlers/men/brutuscreed/brutuscreedfull.png',
    gender: 'Male',
    alignment: 'Face',
    faction: 'American Made',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'SMACKDOWN',
    holdsTitleNames: ['']
  },
  {
    name: 'Carmelo Hayes',
    avatar: './visuals/Wrestlers/men/carmelohayes/carmelohayesavatar.png',
    image: './visuals/Wrestlers/men/carmelohayes/carmelohayesfull.png',
    gender: 'Male',
    alignment: 'Face',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'RAW',
    holdsTitleNames: ['']
  },
  {
    name: 'Cedric Alexander',
    avatar: './visuals/Wrestlers/men/cedricalexander/cedricalexanderavatar.png',
    image: './visuals/Wrestlers/men/cedricalexander/cedricalexanderfull.png',
    gender: 'Male',
    alignment: 'Face',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'RAW',
    holdsTitleNames: ['']
  },
  {
    name: 'Chad Gable',
    avatar: './visuals/Wrestlers/men/chadgable/chadgableavatar.png',
    image: './visuals/Wrestlers/men/chadgable/chadgablefull.png',
    gender: 'Male',
    alignment: 'Face',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'SMACKDOWN',
    holdsTitleNames: ['']
  },
  {
    name: 'Channing Lorenzo',
    avatar: './visuals/Wrestlers/men/channingstackslorenzo/channingstackslorenzoavatar.png',
    image: './visuals/Wrestlers/men/channingstackslorenzo/channingstackslorenzofull.png',
    gender: 'Male',
    alignment: 'Heel',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'NXT',
    holdsTitleNames: ['']
  },
  {
    name: 'Charlie Dempsey',
    avatar: './visuals/Wrestlers/men/charliedempsey/charliedempseyavatar.png',
    image: './visuals/Wrestlers/men/charliedempsey/charliedempseyfull.png',
    gender: 'Male',
    alignment: 'Heel',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'NXT',
    holdsTitleNames: ['']
  },
  {
    name: 'Chris Danger',
    avatar: './visuals/Wrestlers/men/chrisdanger/chrisdangeravatar.png',
    image: './visuals/Wrestlers/men/chrisdanger/chrisdangerfull.png',
    gender: 'Male',
    alignment: 'Heel',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'NXT',
    holdsTitleNames: ['']
  },
  {
    name: 'Chris Jericho',
    avatar: './visuals/Wrestlers/men/chrisjericho/chrisjerichoavatar.png',
    image: './visuals/Wrestlers/men/chrisjericho/chrisjerichofull.png',
    gender: 'Male',
    alignment: 'Heel',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'RAW',
    holdsTitleNames: ['']
  },
  {
    name: 'CM Punk',
    avatar: './visuals/Wrestlers/men/cmpunk/cmpunkavatar.png',
    image: './visuals/Wrestlers/men/cmpunk/cmpunkfull.png',
    gender: 'Male',
    alignment: 'Face',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'SMACKDOWN',
    holdsTitleNames: ['']
  },
  {
    name: 'Cody Rhodes',
    avatar: './visuals/Wrestlers/men/codyrhodes/codyrhodesavatar.png',
    image: './visuals/Wrestlers/men/codyrhodes/codyrhodesfull.png',
    gender: 'Male',
    alignment: 'Face',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'RAW',
    holdsTitleNames: ['']
  },
  {
    name: 'Cruz Del Toro',
    avatar: './visuals/Wrestlers/men/cruzdeltoro/cruzdeltoroavatar.png',
    image: './visuals/Wrestlers/men/cruzdeltoro/cruzdeltorofull.png',
    gender: 'Male',
    alignment: 'Face',
    faction: 'LWO',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'NXT',
    holdsTitleNames: ['']
  },
  {
    name: 'Damian Priest',
    avatar: './visuals/Wrestlers/men/damianpriest/damianpriestavatar.png',
    image: './visuals/Wrestlers/men/damianpriest/damianpriestfull.png',
    gender: 'Male',
    alignment: 'Face',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'RAW',
    holdsTitleNames: ['']
  },
  {
    name: 'Dexter Lumis',
    avatar: './visuals/Wrestlers/men/dexterlumis/dexterlumisavatar.png',
    image: './visuals/Wrestlers/men/dexterlumis/dexterlumisfull.png',
    gender: 'Male',
    alignment: 'Heel',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'NXT',
    holdsTitleNames: ['']
  },
  {
    name: 'Dolph Ziggler',
    avatar: './visuals/Wrestlers/men/dolphziggler/dolphziggleravatar.png',
    image: './visuals/Wrestlers/men/dolphziggler/dolphzigglerfull.png',
    gender: 'Male',
    alignment: 'Heel',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'RAW',
    holdsTitleNames: ['']
  },
  {
    name: 'Dominik Mysterio',
    avatar: './visuals/Wrestlers/men/dominikmysterio/dominikmysterioavatar.png',
    image: './visuals/Wrestlers/men/dominikmysterio/dominikmysteriofull.png',
    gender: 'Male',
    alignment: 'Heel',
    faction: 'Judgment Day',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'SMACKDOWN',
    holdsTitleNames: ['']
  },
  {
    name: 'Dragon Lee',
    avatar: './visuals/Wrestlers/men/dragonlee/dragonleeavatar.png',
    image: './visuals/Wrestlers/men/dragonlee/dragonleefull.png',
    gender: 'Male',
    alignment: 'Face',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'RAW',
    holdsTitleNames: ['']
  },
  {
    name: 'Drew McIntyre',
    avatar: './visuals/Wrestlers/men/drewmcintyre/drewmcintyreavatar.png',
    image: './visuals/Wrestlers/men/drewmcintyre/drewmcintyrefull.png',
    gender: 'Male',
    alignment: 'Heel',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'SMACKDOWN',
    holdsTitleNames: ['']
  },
  {
    name: 'Duke Hudson',
    avatar: './visuals/Wrestlers/men/dukehudson/dukehudsonavatar.png',
    image: './visuals/Wrestlers/men/dukehudson/dukehudsonfull.png',
    gender: 'Male',
    alignment: 'Face',
    faction: 'Chase University',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'NXT',
    holdsTitleNames: ['']
  },
  {
    name: 'Eddy Thorpe',
    avatar: './visuals/Wrestlers/men/eddythorpe/eddythorpeavatar.png',
    image: './visuals/Wrestlers/men/eddythorpe/eddythorpefull.png',
    gender: 'Male',
    alignment: 'Heel',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'NXT',
    holdsTitleNames: ['']
  },
  {
    name: 'Elton Prince',
    avatar: './visuals/Wrestlers/men/eltonprince/eltonprinceavatar.png',
    image: './visuals/Wrestlers/men/eltonprince/eltonprincefull.png',
    gender: 'Male',
    alignment: 'Heel',
    faction: 'Pretty Deadly',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'SMACKDOWN',
    holdsTitleNames: ['']
  },
  {
    name: 'Erik',
    avatar: './visuals/Wrestlers/men/erik/erikavatar.png',
    image: './visuals/Wrestlers/men/erik/erikfull.png',
    gender: 'Male',
    alignment: 'Face',
    faction: 'War Raiders',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'RAW',
    holdsTitleNames: ['']
  },
  {
    name: 'Ethan Page',
    avatar: './visuals/Wrestlers/men/ethanpage/ethanpageavatar.png',
    image: './visuals/Wrestlers/men/ethanpage/ethanpagefull.png',
    gender: 'Male',
    alignment: 'Heel',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'NXT',
    holdsTitleNames: ['']
  },
  {
    name: 'Finn Balor',
    avatar: './visuals/Wrestlers/men/finnbalor/finnbaloravatar.png',
    image: './visuals/Wrestlers/men/finnbalor/finnbalorfull.png',
    gender: 'Male',
    alignment: 'Heel',
    faction: 'Judgment Day',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'SMACKDOWN',
    holdsTitleNames: ['']
  },
  {
    name: 'Giovanni Vinci',
    avatar: './visuals/Wrestlers/men/giovannivinci/giovannivinciavatar.png',
    image: './visuals/Wrestlers/men/giovannivinci/giovannivincifull.png',
    gender: 'Male',
    alignment: 'Heel',
    faction: 'Imperium',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'NXT',
    holdsTitleNames: ['']
  },
  {
    name: 'Grayson Waller',
    avatar: './visuals/Wrestlers/men/graysonwaller/graysonwalleravatar.png',
    image: './visuals/Wrestlers/men/graysonwaller/graysonwallerfull.png',
    gender: 'Male',
    alignment: 'Heel',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'NXT',
    holdsTitleNames: ['']
  },
  {
    name: 'Günther',
    avatar: './visuals/Wrestlers/men/gunther/guntheravatar.png',
    image: './visuals/Wrestlers/men/gunther/guntherfull.png',
    gender: 'Male',
    alignment: 'Heel',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'RAW',
    holdsTitleNames: ['']
  },
  {
    name: 'Ilja Dragunov',
    avatar: './visuals/Wrestlers/men/iljadragunov/iljadragunovavatar.png',
    image: './visuals/Wrestlers/men/iljadragunov/iljadragunovfull.png',
    gender: 'Male',
    alignment: 'Face',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'RAW',
    holdsTitleNames: ['']
  },
  {
    name: 'Ivar',
    avatar: './visuals/Wrestlers/men/ivar/ivaravatar.png',
    image: './visuals/Wrestlers/men/ivar/ivarfull.png',
    gender: 'Male',
    alignment: 'Face',
    faction: 'War Raiders',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'RAW',
    holdsTitleNames: ['']
  },
  {
    name: 'Jacob Fatu',
    avatar: './visuals/Wrestlers/men/jacobfatu/jacobfatuavatar.png',
    image: './visuals/Wrestlers/men/jacobfatu/jacobfatufull.png',
    gender: 'Male',
    alignment: 'Face',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'RAW',
    holdsTitleNames: ['']
  },
  {
    name: 'JD McDonagh',
    avatar: './visuals/Wrestlers/men/jdmcdonagh/jdmcdonaghavatar.png',
    image: './visuals/Wrestlers/men/jdmcdonagh/jdmcdonaghfull.png',
    gender: 'Male',
    alignment: 'Heel',
    faction: 'Judgment Day',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'NXT',
    holdsTitleNames: ['']
  },
  {
    name: 'Jeff Hardy',
    avatar: './visuals/Wrestlers/men/jeffhardy/jeffhardyavatar.png',
    image: './visuals/Wrestlers/men/jeffhardy/jeffhardyfull.png',
    gender: 'Male',
    alignment: 'Face',
    faction: 'Hardy Boyz',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'NXT',
    holdsTitleNames: ['']
  },
  {
    name: "Je'von Evans",
    avatar: './visuals/Wrestlers/men/jevonevans/jevonevansavatar.png',
    image: './visuals/Wrestlers/men/jevonevans/jevonevansfull.png',
    gender: 'Male',
    alignment: 'Face',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'RAW',
    holdsTitleNames: ['']
  },
  {
    name: 'Jey Uso',
    avatar: './visuals/Wrestlers/men/jeyuso/jeyusoavatar.png',
    image: './visuals/Wrestlers/men/jeyuso/jeyusofull.png',
    gender: 'Male',
    alignment: 'Face',
    faction: 'The Usos',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'SMACKDOWN',
    holdsTitleNames: ['']
  },
  {
    name: 'Jimmy Uso',
    avatar: './visuals/Wrestlers/men/jimmyuso/jimmyusoavatar.png',
    image: './visuals/Wrestlers/men/jimmyuso/jimmyusofull.png',
    gender: 'Male',
    alignment: 'Face',
    faction: 'The Usos',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'SMACKDOWN',
    holdsTitleNames: ['']
  },
  {
    name: 'Joaquin Wilde',
    avatar: './visuals/Wrestlers/men/joaquinwilde/joaquinwildeavatar.png',
    image: './visuals/Wrestlers/men/joaquinwilde/joaquinwildefull.png',
    gender: 'Male',
    alignment: 'Face',
    faction: 'LWO',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'NXT',
    holdsTitleNames: ['']
  },
  {
    name: 'Joe Coffey',
    avatar: './visuals/Wrestlers/men/joecoffey/joecoffeyavatar.png',
    image: './visuals/Wrestlers/men/joecoffey/joecoffeyfull.png',
    gender: 'Male',
    alignment: 'Heel',
    faction: 'Gallus',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'NXT',
    holdsTitleNames: ['']
  },
  {
    name: 'Joe Gacy',
    avatar: './visuals/Wrestlers/men/joegacy/joegacyavatar.png',
    image: './visuals/Wrestlers/men/joegacy/joegacyfull.png',
    gender: 'Male',
    alignment: 'Heel',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'SMACKDOWN',
    holdsTitleNames: ['']
  },
  {
    name: 'Joe Hendry',
    avatar: './visuals/Wrestlers/men/joehendry/joehendryavatar.png',
    image: './visuals/Wrestlers/men/joehendry/joehendryfull.png',
    gender: 'Male',
    alignment: 'Face',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'NXT',
    holdsTitleNames: ['']
  },
  {
    name: 'John Cena',
    avatar: './visuals/Wrestlers/men/johncena/johncenaavatar.png',
    image: './visuals/Wrestlers/men/johncena/johncenafull.png',
    gender: 'Male',
    alignment: 'Face',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'RAW',
    holdsTitleNames: ['']
  },
  {
    name: 'Johnny Gargano',
    avatar: './visuals/Wrestlers/men/johnnygargano/johnnygarganoavatar.png',
    image: './visuals/Wrestlers/men/johnnygargano/johnnygarganofull.png',
    gender: 'Male',
    alignment: 'Face',
    faction: '#DIY',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'RAW',
    holdsTitleNames: ['']
  },
  {
    name: 'Josh Briggs',
    avatar: './visuals/Wrestlers/men/joshbriggs/joshbriggsavatar.png',
    image: './visuals/Wrestlers/men/joshbriggs/joshbriggsfull.png',
    gender: 'Male',
    alignment: 'Face',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'SMACKDOWN',
    holdsTitleNames: ['']
  },
  {
    name: 'Julius Creed',
    avatar: './visuals/Wrestlers/men/juliuscreed/juliuscreedavatar.png',
    image: './visuals/Wrestlers/men/juliuscreed/juliuscreedfull.png',
    gender: 'Male',
    alignment: 'Heel',
    faction: 'American Made',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'SMACKDOWN',
    holdsTitleNames: ['']
  },
  {
    name: 'Karl Anderson',
    avatar: './visuals/Wrestlers/men/karlanderson/karlandersonavatar.png',
    image: './visuals/Wrestlers/men/karlanderson/karlandersonfull.png',
    gender: 'Male',
    alignment: 'Heel',
    faction: 'The O.C.',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'RAW',
    holdsTitleNames: ['']
  },
  {
    name: 'Karrion Kross',
    avatar: './visuals/Wrestlers/men/karrionkross/karrionkrossavatar.png',
    image: './visuals/Wrestlers/men/karrionkross/karrionkrossfull.png',
    gender: 'Male',
    alignment: 'Heel',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'NXT',
    holdsTitleNames: ['']
  },
  {
    name: 'Kenny Omega',
    avatar: './visuals/Wrestlers/men/kennyomega/kennyomegaavatar.png',
    image: './visuals/Wrestlers/men/kennyomega/kennyomegafull.png',
    gender: 'Male',
    alignment: 'Face',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'SMACKDOWN',
    holdsTitleNames: ['']
  },
  {
    name: 'Kevin Owens',
    avatar: './visuals/Wrestlers/men/kevinowens/kevinowensavatar.png',
    image: './visuals/Wrestlers/men/kevinowens/kevinowensfull.png',
    gender: 'Male',
    alignment: 'Face',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'SMACKDOWN',
    holdsTitleNames: ['']
  },
  {
    name: 'Kit Wilson',
    avatar: './visuals/Wrestlers/men/kitwilson/kitwilsonavatar.png',
    image: './visuals/Wrestlers/men/kitwilson/kitwilsonfull.png',
    gender: 'Male',
    alignment: 'Heel',
    faction: 'Pretty Deadly',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'SMACKDOWN',
    holdsTitleNames: ['']
  },
  {
    name: 'Kofi Kingston',
    avatar: './visuals/Wrestlers/men/kofikingston/kofikingstonavatar.png',
    image: './visuals/Wrestlers/men/kofikingston/kofikingstonfull.png',
    gender: 'Male',
    alignment: 'Face',
    faction: 'The New Day',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'RAW',
    holdsTitleNames: ['']
  },
  {
    name: "Kyle O'Reilly",
    avatar: './visuals/Wrestlers/men/kyleoreilly/kyleoreillyavatar.png',
    image: './visuals/Wrestlers/men/kyleoreilly/kyleoreillyfull.png',
    gender: 'Male',
    alignment: 'Face',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'NXT',
    holdsTitleNames: ['']
  },
  {
    name: 'L.A. Knight',
    avatar: './visuals/Wrestlers/men/laknight/laknightavatar.png',
    image: './visuals/Wrestlers/men/laknight/laknightfull.png',
    gender: 'Male',
    alignment: 'Face',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'SMACKDOWN',
    holdsTitleNames: ['']
  },
  {
    name: 'Lexis King',
    avatar: './visuals/Wrestlers/men/lexisking/lexiskingavatar.png',
    image: './visuals/Wrestlers/men/lexisking/lexiskingfull.png',
    gender: 'Male',
    alignment: 'Heel',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'NXT',
    holdsTitleNames: ['']
  },
  {
    name: 'Logan Paul',
    avatar: './visuals/Wrestlers/men/loganpaul/loganpaulavatar.png',
    image: './visuals/Wrestlers/men/loganpaul/loganpaulfull.png',
    gender: 'Male',
    alignment: 'Heel',
    faction: 'The Vision',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'SMACKDOWN',
    holdsTitleNames: ['']
  },
  {
    name: 'Ludwig Kaiser',
    avatar: './visuals/Wrestlers/men/ludwigkaiser/ludwigkaiseravatar.png',
    image: './visuals/Wrestlers/men/ludwigkaiser/ludwigkaiserfull.png',
    gender: 'Male',
    alignment: 'Heel',
    faction: 'Imperium',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'NXT',
    holdsTitleNames: ['']
  },
  {
    name: 'Luke Gallows',
    avatar: './visuals/Wrestlers/men/lukegallows/lukegallowsavatar.png',
    image: './visuals/Wrestlers/men/lukegallows/lukegallowsfull.png',
    gender: 'Male',
    alignment: 'Heel',
    faction: 'The O.C.',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'RAW',
    holdsTitleNames: ['']
  },
  {
    name: 'Malakai Black',
    avatar: './visuals/Wrestlers/men/malakaiblack/malakaiblackavatar.png',
    image: './visuals/Wrestlers/men/malakaiblack/malakaiblackfull.png',
    gender: 'Male',
    alignment: 'Heel',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'RAW',
    holdsTitleNames: ['']
  },
  {
    name: 'Mark Coffey',
    avatar: './visuals/Wrestlers/men/markcoffey/markcoffeyavatar.png',
    image: './visuals/Wrestlers/men/markcoffey/markcoffeyfull.png',
    gender: 'Male',
    alignment: 'Heel',
    faction: 'Gallus',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'NXT',
    holdsTitleNames: ['']
  },
  {
    name: 'Matt Hardy',
    avatar: './visuals/Wrestlers/men/matthardy/matthardyavatar.png',
    image: './visuals/Wrestlers/men/matthardy/matthardyfull.png',
    gender: 'Male',
    alignment: 'Face',
    faction: 'Hardy Boyz',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'NXT',
    holdsTitleNames: ['']
  },
  {
    name: 'Montez Ford',
    avatar: './visuals/Wrestlers/men/montezford/montezfordavatar.png',
    image: './visuals/Wrestlers/men/montezford/montezfordfull.png',
    gender: 'Male',
    alignment: 'Face',
    faction: 'Street Profits',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'SMACKDOWN',
    holdsTitleNames: ['']
  },
  {
    name: 'Mr. Iguana',
    avatar: './visuals/Wrestlers/men/mriguana/mriguanaavatar.png',
    image: './visuals/Wrestlers/men/mriguana/mriguanafull.png',
    gender: 'Male',
    alignment: 'Face',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'NXT',
    holdsTitleNames: ['']
  },
  {
    name: 'Nathan Frazer',
    avatar: './visuals/Wrestlers/men/nathanfrazer/nathanfrazeravatar.png',
    image: './visuals/Wrestlers/men/nathanfrazer/nathanfrazerfull.png',
    gender: 'Male',
    alignment: 'Face',
    faction: 'Fraxiom',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'SMACKDOWN',
    holdsTitleNames: ['']
  },
  {
    name: 'Noam Dar',
    avatar: './visuals/Wrestlers/men/noamdar/noamdaravatar.png',
    image: './visuals/Wrestlers/men/noamdar/noamdarfull.png',
    gender: 'Male',
    alignment: 'Heel',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'RAW',
    holdsTitleNames: ['']
  },
  {
    name: 'Oba Femi',
    avatar: './visuals/Wrestlers/men/obafemi/obafemiavatar.png',
    image: './visuals/Wrestlers/men/obafemi/obafemifull.png',
    gender: 'Male',
    alignment: 'Face',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'RAW',
    holdsTitleNames: ['']
  },
  {
    name: 'Omos',
    avatar: './visuals/Wrestlers/men/omos/omosavatar.png',
    image: './visuals/Wrestlers/men/omos/omosfull.png',
    gender: 'Male',
    alignment: 'Heel',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'NXT',
    holdsTitleNames: ['']
  },
  {
    name: 'Oro Mensah',
    avatar: './visuals/Wrestlers/men/oromensah/oromensahavatar.png',
    image: './visuals/Wrestlers/men/oromensah/oromensahfull.png',
    gender: 'Male',
    alignment: 'Face',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'NXT',
    holdsTitleNames: ['']
  },
  {
    name: 'Otis',
    avatar: './visuals/Wrestlers/men/otis/otisavatar.png',
    image: './visuals/Wrestlers/men/otis/otisfull.png',
    gender: 'Male',
    alignment: 'Face',
    faction: 'Alpha Academy',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'RAW',
    holdsTitleNames: ['']
  },
  {
    name: 'Paragon Jay Pierce',
    avatar: './visuals/Wrestlers/men/paragonjaypierce/paragonjaypierceavatar.png',
    image: './visuals/Wrestlers/men/paragonjaypierce/paragonjaypiercefull.png',
    gender: 'Male',
    alignment: 'Face',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'NXT',
    holdsTitleNames: ['']
  },
  {
    name: 'Penta',
    avatar: './visuals/Wrestlers/men/penta/pentaavatar.png',
    image: './visuals/Wrestlers/men/penta/pentafull.png',
    gender: 'Male',
    alignment: 'Face',
    faction: 'Lucha Brothers',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'RAW',
    holdsTitleNames: ['']
  },
  {
    name: 'Pete Dunne',
    avatar: './visuals/Wrestlers/men/petedunne/petedunneavatar.png',
    image: './visuals/Wrestlers/men/petedunne/petedunnefull.png',
    gender: 'Male',
    alignment: 'Face',
    faction: 'New Catch Republic',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'SMACKDOWN',
    holdsTitleNames: ['']
  },
  {
    name: 'Randy Orton',
    avatar: './visuals/Wrestlers/men/randyorton/randyortonavatar.png',
    image: './visuals/Wrestlers/men/randyorton/randyortonfull.png',
    gender: 'Male',
    alignment: 'Face',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'RAW',
    holdsTitleNames: ['']
  },
  {
    name: 'Rey Fenix',
    avatar: './visuals/Wrestlers/men/reyfenix/reyfenixavatar.png',
    image: './visuals/Wrestlers/men/reyfenix/reyfenixfull.png',
    gender: 'Male',
    alignment: 'Face',
    faction: 'Lucha Brothers',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'RAW',
    holdsTitleNames: ['']
  },
  {
    name: 'Rey Mysterio',
    avatar: './visuals/Wrestlers/men/reymysterio/reymysterioavatar.png',
    image: './visuals/Wrestlers/men/reymysterio/reymysteriofull.png',
    gender: 'Male',
    alignment: 'Face',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'SMACKDOWN',
    holdsTitleNames: ['']
  },
  {
    name: 'Rezar',
    avatar: './visuals/Wrestlers/men/rezar/rezaravatar.png',
    image: './visuals/Wrestlers/men/rezar/rezarfull.png',
    gender: 'Male',
    alignment: 'Heel',
    faction: 'Authors of Pain',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'RAW',
    holdsTitleNames: ['']
  },
  {
    name: 'Ricky Saints',
    avatar: './visuals/Wrestlers/men/rickysaints/rickysaintsavatar.png',
    image: './visuals/Wrestlers/men/rickysaints/rickysaintsfull.png',
    gender: 'Male',
    alignment: 'Face',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'NXT',
    holdsTitleNames: ['']
  },
  {
    name: 'Ridge Holland',
    avatar: './visuals/Wrestlers/men/ridgeholland/ridgehollandavatar.png',
    image: './visuals/Wrestlers/men/ridgeholland/ridgehollandfull.png',
    gender: 'Male',
    alignment: 'Heel',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'SMACKDOWN',
    holdsTitleNames: ['']
  },
  {
    name: 'Roman Reigns',
    avatar: './visuals/Wrestlers/men/romanreigns/romanreignsavatar.png',
    image: './visuals/Wrestlers/men/romanreigns/romanreignsfull.png',
    gender: 'Male',
    alignment: 'Heel',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'SMACKDOWN',
    holdsTitleNames: ['']
  },
  {
    name: 'R-Truth',
    avatar: './visuals/Wrestlers/men/rtruth/rtruthavatar.png',
    image: './visuals/Wrestlers/men/rtruth/rtruthfull.png',
    gender: 'Male',
    alignment: 'Face',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'RAW',
    holdsTitleNames: ['']
  },
  {
    name: 'Rusev',
    avatar: './visuals/Wrestlers/men/rusev/rusevavatar.png',
    image: './visuals/Wrestlers/men/rusev/rusevfull.png',
    gender: 'Male',
    alignment: 'Heel',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'NXT',
    holdsTitleNames: ['']
  },
  {
    name: 'Sami Zayn',
    avatar: './visuals/Wrestlers/men/samizayn/samizaynavatar.png',
    image: './visuals/Wrestlers/men/samizayn/samizaynfull.png',
    gender: 'Male',
    alignment: 'Face',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'SMACKDOWN',
    holdsTitleNames: ['']
  },
  {
    name: 'Santos Escobar',
    avatar: './visuals/Wrestlers/men/santosescobar/santosescobaravatar.png',
    image: './visuals/Wrestlers/men/santosescobar/santosescobarfull.png',
    gender: 'Male',
    alignment: 'Heel',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'NXT',
    holdsTitleNames: ['']
  },
  {
    name: 'Seth Rollins',
    avatar: './visuals/Wrestlers/men/sethrollins/sethrollinsavatar.png',
    image: './visuals/Wrestlers/men/sethrollins/sethrollinsfull.png',
    gender: 'Male',
    alignment: 'Heel',
    faction: 'The Vision',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'SMACKDOWN',
    holdsTitleNames: ['']
  },
  {
    name: 'Shawn Spears',
    avatar: './visuals/Wrestlers/men/shawnspears/shawnspearsavatar.png',
    image: './visuals/Wrestlers/men/shawnspears/shawnspearsfull.png',
    gender: 'Male',
    alignment: 'Heel',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'SMACKDOWN',
    holdsTitleNames: ['']
  },
  {
    name: 'Sheamus',
    avatar: './visuals/Wrestlers/men/sheamus/sheamusavatar.png',
    image: './visuals/Wrestlers/men/sheamus/sheamusfull.png',
    gender: 'Male',
    alignment: 'Face',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'SMACKDOWN',
    holdsTitleNames: ['']
  },
  {
    name: 'Shinsuke Nakamura',
    avatar: './visuals/Wrestlers/men/shinsukenakamura/shinsukenakamuraavatar.png',
    image: './visuals/Wrestlers/men/shinsukenakamura/shinsukenakamurafull.png',
    gender: 'Male',
    alignment: 'Face',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'SMACKDOWN',
    holdsTitleNames: ['']
  },
  {
    name: 'Solo Sikoa',
    avatar: './visuals/Wrestlers/men/solosikoa/solosikoaavatar.png',
    image: './visuals/Wrestlers/men/solosikoa/solosikoafull.png',
    gender: 'Male',
    alignment: 'Heel',
    faction: 'MFT',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'NXT',
    holdsTitleNames: ['']
  },
  {
    name: 'Tama Tonga',
    avatar: './visuals/Wrestlers/men/tamatonga/tamatongaavatar.png',
    image: './visuals/Wrestlers/men/tamatonga/tamatongafull.png',
    gender: 'Male',
    alignment: 'Heel',
    faction: 'MFT',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'NXT',
    holdsTitleNames: ['']
  },
  {
    name: 'The Miz',
    avatar: './visuals/Wrestlers/men/themiz/themizavatar.png',
    image: './visuals/Wrestlers/men/themiz/themizfull.png',
    gender: 'Male',
    alignment: 'Heel',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'RAW',
    holdsTitleNames: ['']
  },
  {
    name: 'Tommaso Ciampa',
    avatar: './visuals/Wrestlers/men/tommasociampa/tommasociampaavatar.png',
    image: './visuals/Wrestlers/men/tommasociampa/tommasociampafull.png',
    gender: 'Male',
    alignment: 'Heel',
    faction: '#DIY',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'RAW',
    holdsTitleNames: ['']
  },
  {
    name: 'Tonga Loa',
    avatar: './visuals/Wrestlers/men/tongaloa/tongaloaavatar.png',
    image: './visuals/Wrestlers/men/tongaloa/tongaloafull.png',
    gender: 'Male',
    alignment: 'Heel',
    faction: 'MFT',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'NXT',
    holdsTitleNames: ['']
  },
  {
    name: "Tony D'Angelo",
    avatar: './visuals/Wrestlers/men/tonydangelo/tonydangeloavatar.png',
    image: './visuals/Wrestlers/men/tonydangelo/tonydangelofull.png',
    gender: 'Male',
    alignment: 'Heel',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'NXT',
    holdsTitleNames: ['']
  },
  {
    name: 'Trey Miguel',
    avatar: './visuals/Wrestlers/men/treymiguel/treymiguelavatar.png',
    image: './visuals/Wrestlers/men/treymiguel/treymiguelfull.png',
    gender: 'Male',
    alignment: 'Face',
    faction: 'The Rascalz',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'NXT',
    holdsTitleNames: ['']
  },
  {
    name: 'Trick Williams',
    avatar: './visuals/Wrestlers/men/trickwilliams/trickwilliamsavatar.png',
    image: './visuals/Wrestlers/men/trickwilliams/trickwilliamsfull.png',
    gender: 'Male',
    alignment: 'Face',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'RAW',
    holdsTitleNames: ['']
  },
  {
    name: 'Tyler Bate',
    avatar: './visuals/Wrestlers/men/tylerbate/tylerbateavatar.png',
    image: './visuals/Wrestlers/men/tylerbate/tylerbatefull.png',
    gender: 'Male',
    alignment: 'Face',
    faction: 'New Catch Republic',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'SMACKDOWN',
    holdsTitleNames: ['']
  },
  {
    name: 'Tyler Breeze',
    avatar: './visuals/Wrestlers/men/tylerbreeze/tylerbreezeavatar.png',
    image: './visuals/Wrestlers/men/tylerbreeze/tylerbreezefull.png',
    gender: 'Male',
    alignment: 'Heel',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'RAW',
    holdsTitleNames: ['']
  },
  {
    name: 'Wes Lee',
    avatar: './visuals/Wrestlers/men/weslee/wesleeavatar.png',
    image: './visuals/Wrestlers/men/weslee/wesleefull.png',
    gender: 'Male',
    alignment: 'Face',
    faction: 'The Rascalz',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'NXT',
    holdsTitleNames: ['']
  },
  {
    name: 'Wolfgang',
    avatar: './visuals/Wrestlers/men/wolfgang/wolfgangavatar.png',
    image: './visuals/Wrestlers/men/wolfgang/wolfgangfull.png',
    gender: 'Male',
    alignment: 'Heel',
    faction: 'Gallus',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'NXT',
    holdsTitleNames: ['']
  },
  {
    name: 'Xavier Woods',
    avatar: './visuals/Wrestlers/men/xavierwoods/xavierwoodsavatar.png',
    image: './visuals/Wrestlers/men/xavierwoods/xavierwoodsfull.png',
    gender: 'Male',
    alignment: 'Face',
    faction: 'The New Day',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'RAW',
    holdsTitleNames: ['']
  },
  {
    name: 'Zach Wentz',
    avatar: './visuals/Wrestlers/men/zachwentz/zachwentzavatar.png',
    image: './visuals/Wrestlers/men/zachwentz/zachwentzfull.png',
    gender: 'Male',
    alignment: 'Face',
    faction: 'The Rascalz',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'NXT',
    holdsTitleNames: ['']
  },

  {
    name: 'Alba Fyre',
    avatar: './visuals/Wrestlers/women/albafyre/albafyreavatar.png',
    image: './visuals/Wrestlers/women/albafyre/albafyrefull.png',
    gender: 'Female',
    alignment: 'Heel',
    faction: 'ServiceHer',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'NXT',
    holdsTitleNames: ['']
  },
  {
    name: 'Alexa Bliss',
    avatar: './visuals/Wrestlers/women/alexabliss/alexablissavatar.png',
    image: './visuals/Wrestlers/women/alexabliss/alexablissfull.png',
    gender: 'Female',
    alignment: 'Face',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'RAW',
    holdsTitleNames: ['']
  },
  {
    name: 'Asuka',
    avatar: './visuals/Wrestlers/women/asuka/asukaavatar.png',
    image: './visuals/Wrestlers/women/asuka/asukafull.png',
    gender: 'Female',
    alignment: 'Heel',
    faction: 'Kabuki Warriors',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'SMACKDOWN',
    holdsTitleNames: ['']
  },
  {
    name: 'Bayley',
    avatar: './visuals/Wrestlers/women/bayley/bayleyavatar.png',
    image: './visuals/Wrestlers/women/bayley/bayleyfull.png',
    gender: 'Female',
    alignment: 'Face',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'RAW',
    holdsTitleNames: ['']
  },
  {
    name: 'Becky Lynch',
    avatar: './visuals/Wrestlers/women/beckylynch/beckylynchavatar.png',
    image: './visuals/Wrestlers/women/beckylynch/beckylynchfull.png',
    gender: 'Female',
    alignment: 'Heel',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'RAW',
    holdsTitleNames: ['']
  },
  {
    name: 'B-Fab',
    avatar: './visuals/Wrestlers/women/bfab/bfabavatar.png',
    image: './visuals/Wrestlers/women/bfab/bfabfull.png',
    gender: 'Female',
    alignment: 'Face',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'NXT',
    holdsTitleNames: ['']
  },
  {
    name: 'Bianca Belair',
    avatar: './visuals/Wrestlers/women/biancabelair/biancabelairavatar.png',
    image: './visuals/Wrestlers/women/biancabelair/biancabelairfull.png',
    gender: 'Female',
    alignment: 'Face',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'RAW',
    holdsTitleNames: ['']
  },
  {
    name: 'Blair Davenport',
    avatar: './visuals/Wrestlers/women/blairdavenport/blairdavenportavatar.png',
    image: './visuals/Wrestlers/women/blairdavenport/blairdavenportfull.png',
    gender: 'Female',
    alignment: 'Heel',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'SMACKDOWN',
    holdsTitleNames: ['']
  },
  {
    name: 'Blake Monroe',
    avatar: './visuals/Wrestlers/women/blakemonroe/blakemonroeavatar.png',
    image: './visuals/Wrestlers/women/blakemonroe/blakemonroefull.png',
    gender: 'Female',
    alignment: 'Face',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'NXT',
    holdsTitleNames: ['']
  },
  {
    name: 'Brie Bella',
    avatar: './visuals/Wrestlers/women/briebella/briebellaavatar.png',
    image: './visuals/Wrestlers/women/briebella/briebellafull.png',
    gender: 'Female',
    alignment: 'Face',
    faction: 'Bella Twins',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'RAW',
    holdsTitleNames: ['']
  },
  {
    name: 'Candice Lerae',
    avatar: './visuals/Wrestlers/women/candicelerae/candiceleraeavatar.png',
    image: './visuals/Wrestlers/women/candicelerae/candiceleraefull.png',
    gender: 'Female',
    alignment: 'Heel',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'RAW',
    holdsTitleNames: ['']
  },
  {
    name: 'Charlotte Flair',
    avatar: './visuals/Wrestlers/women/charlotteflair/charlotteflairavatar.png',
    image: './visuals/Wrestlers/women/charlotteflair/charlotteflairfull.png',
    gender: 'Female',
    alignment: 'Heel',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'SMACKDOWN',
    holdsTitleNames: ['']
  },
  {
    name: 'Chelsea Green',
    avatar: './visuals/Wrestlers/women/chelseagreen/chelseagreenavatar.png',
    image: './visuals/Wrestlers/women/chelseagreen/chelseagreenfull.png',
    gender: 'Female',
    alignment: 'Heel',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'SMACKDOWN',
    holdsTitleNames: ['']
  },
  {
    name: 'Carmella',
    avatar: './visuals/Wrestlers/women/carmella/carmellaavatar.png',
    image: './visuals/Wrestlers/women/carmella/carmellafull.png',
    gender: 'Female',
    alignment: 'Heel',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'RAW',
    holdsTitleNames: ['']
  },
  {
    name: 'Cora Jade',
    avatar: './visuals/Wrestlers/women/corajade/corajadeavatar.png',
    image: './visuals/Wrestlers/women/corajade/corajadefull.png',
    gender: 'Female',
    alignment: 'Heel',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'NXT',
    holdsTitleNames: ['']
  },
  {
    name: 'Dakota Kai',
    avatar: './visuals/Wrestlers/women/dakotakai/dakotakaiavatar.png',
    image: './visuals/Wrestlers/women/dakotakai/dakotakaifull.png',
    gender: 'Female',
    alignment: 'Face',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'NXT',
    holdsTitleNames: ['']
  },
  {
    name: 'Elektra Lopez',
    avatar: './visuals/Wrestlers/women/elektralopez/elektralopezavatar.png',
    image: './visuals/Wrestlers/women/elektralopez/elektralopezfull.png',
    gender: 'Female',
    alignment: 'Heel',
    faction: 'Los Garza',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'NXT',
    holdsTitleNames: ['']
  },
  {
    name: 'Fallon Henley',
    avatar: './visuals/Wrestlers/women/fallonhenley/fallonhenleyavatar.png',
    image: './visuals/Wrestlers/women/fallonhenley/fallonhenleyfull.png',
    gender: 'Female',
    alignment: 'Heel',
    faction: 'Fatal Influence',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'SMACKDOWN',
    holdsTitleNames: ['']
  },
  {
    name: 'Gigi Dolin',
    avatar: './visuals/Wrestlers/women/gigidolin/gigidolinavatar.png',
    image: './visuals/Wrestlers/women/gigidolin/gigidolinfull.png',
    gender: 'Female',
    alignment: 'Face',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'SMACKDOWN',
    holdsTitleNames: ['']
  },
  {
    name: 'Giulia',
    avatar: './visuals/Wrestlers/women/giulia/giuliaavatar.png',
    image: './visuals/Wrestlers/women/giulia/giuliafull.png',
    gender: 'Female',
    alignment: 'Face',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'NXT',
    holdsTitleNames: ['']
  },
  {
    name: 'Indi Hartwell',
    avatar: './visuals/Wrestlers/women/indihartwell/indihartwellavatar.png',
    image: './visuals/Wrestlers/women/indihartwell/indihartwellfull.png',
    gender: 'Female',
    alignment: 'Face',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'NXT',
    holdsTitleNames: ['']
  },
  {
    name: 'Isla Dawn',
    avatar: './visuals/Wrestlers/women/isladawn/isladawnavatar.png',
    image: './visuals/Wrestlers/women/isladawn/isladawnfull.png',
    gender: 'Female',
    alignment: 'Face',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'RAW',
    holdsTitleNames: ['']
  },
  {
    name: 'Ivy Nile',
    avatar: './visuals/Wrestlers/women/ivynile/ivynileavatar.png',
    image: './visuals/Wrestlers/women/ivynile/ivynilefull.png',
    gender: 'Female',
    alignment: 'Heel',
    faction: 'American Made',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'SMACKDOWN',
    holdsTitleNames: ['']
  },
  {
    name: 'Iyo Sky',
    avatar: './visuals/Wrestlers/women/iyosky/iyoskyavatar.png',
    image: './visuals/Wrestlers/women/iyosky/iyoskyfull.png',
    gender: 'Female',
    alignment: 'Face',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'SMACKDOWN',
    holdsTitleNames: ['']
  },
  {
    name: 'Jacy Jayne',
    avatar: './visuals/Wrestlers/women/jacyjayne/jacyjayneavatar.png',
    image: './visuals/Wrestlers/women/jacyjayne/jacyjaynefull.png',
    gender: 'Female',
    alignment: 'Heel',
    faction: 'Fatal Influence',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'SMACKDOWN',
    holdsTitleNames: ['']
  },
  {
    name: 'Jade Cargill',
    avatar: './visuals/Wrestlers/women/jadecargill/jadecargillavatar.png',
    image: './visuals/Wrestlers/women/jadecargill/jadecargillfull.png',
    gender: 'Female',
    alignment: 'Heel',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'SMACKDOWN',
    holdsTitleNames: ['']
  },
  {
    name: 'Jaida Parker',
    avatar: './visuals/Wrestlers/women/jaidaparker/jaidaparkeravatar.png',
    image: './visuals/Wrestlers/women/jaidaparker/jaidaparkerfull.png',
    gender: 'Female',
    alignment: 'Face',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'SMACKDOWN',
    holdsTitleNames: ['']
  },
  {
    name: 'Jakara Jackson',
    avatar: './visuals/Wrestlers/women/jakarajackson/jakarajacksonavatar.png',
    image: './visuals/Wrestlers/women/jakarajackson/jakarajacksonfull.png',
    gender: 'Female',
    alignment: 'Face',
    faction: 'Meta-Two',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'SMACKDOWN',
    holdsTitleNames: ['']
  },
  {
    name: 'Josie Jane',
    avatar: './visuals/Wrestlers/women/josiejane/josiejaneavatar.png',
    image: './visuals/Wrestlers/women/josiejane/josiejanefull.png',
    gender: 'Female',
    alignment: 'Face',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'NXT',
    holdsTitleNames: ['']
  },
  {
    name: 'Kairi Sane',
    avatar: './visuals/Wrestlers/women/kairisane/kairisaneavatar.png',
    image: './visuals/Wrestlers/women/kairisane/kairisanefull.png',
    gender: 'Female',
    alignment: 'Heel',
    faction: 'Kabuki Warriors',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'SMACKDOWN',
    holdsTitleNames: ['']
  },
  {
    name: 'Katana Chance',
    avatar: './visuals/Wrestlers/women/katanachance/katanachanceavatar.png',
    image: './visuals/Wrestlers/women/katanachance/katanachancefull.png',
    gender: 'Female',
    alignment: 'Face',
    faction: 'Party Tag',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'RAW',
    holdsTitleNames: ['']
  },
  {
    name: 'Kayden Carter',
    avatar: './visuals/Wrestlers/women/kaydencarter/kaydencarteravatar.png',
    image: './visuals/Wrestlers/women/kaydencarter/kaydencarterfull.png',
    gender: 'Female',
    alignment: 'Face',
    faction: 'Party Tag',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'RAW',
    holdsTitleNames: ['']
  },
  {
    name: 'Kelani Jordan',
    avatar: './visuals/Wrestlers/women/kelanijordan/kelanijordanavatar.png',
    image: './visuals/Wrestlers/women/kelanijordan/kelanijordantfull.png',
    gender: 'Female',
    alignment: 'Face',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'NXT',
    holdsTitleNames: ['']
  },
  {
    name: 'Kiana James',
    avatar: './visuals/Wrestlers/women/kianajames/kianajamesavatar.png',
    image: './visuals/Wrestlers/women/kianajames/kianajamesfull.png',
    gender: 'Female',
    alignment: 'Heel',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'NXT',
    holdsTitleNames: ['']
  },
  {
    name: 'Lash Legend',
    avatar: './visuals/Wrestlers/women/lashlegend/lashlegendavatar.png',
    image: './visuals/Wrestlers/women/lashlegend/lashlegendfull.png',
    gender: 'Female',
    alignment: 'Face',
    faction: 'Meta-Two',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'SMACKDOWN',
    holdsTitleNames: ['']
  },
  {
    name: 'Liv Morgan',
    avatar: './visuals/Wrestlers/women/livmorgan/livmorganavatar.png',
    image: './visuals/Wrestlers/women/livmorgan/livmorganfull.png',
    gender: 'Female',
    alignment: 'Heel',
    faction: 'Judgment Day',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'RAW',
    holdsTitleNames: ['']
  },
  {
    name: 'Lola Vice',
    avatar: './visuals/Wrestlers/women/lolavice/lolaviceavatar.png',
    image: './visuals/Wrestlers/women/lolavice/lolavicefull.png',
    gender: 'Female',
    alignment: 'Face',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'NXT',
    holdsTitleNames: ['']
  },
  {
    name: 'Lyra Valkyria',
    avatar: './visuals/Wrestlers/women/lyravalkyria/lyravalkyriaavatar.png',
    image: './visuals/Wrestlers/women/lyravalkyria/lyravalkyriafull.png',
    gender: 'Female',
    alignment: 'Face',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'RAW',
    holdsTitleNames: ['']
  },
  {
    name: 'Maxxine Dupri',
    avatar: './visuals/Wrestlers/women/maxxinedupri/maxxinedupriavatar.png',
    image: './visuals/Wrestlers/women/maxxinedupri/maxxineduprifull.png',
    gender: 'Female',
    alignment: 'Face',
    faction: 'Alpha Academy',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'RAW',
    holdsTitleNames: ['']
  },
  {
    name: 'Michin',
    avatar: './visuals/Wrestlers/women/michin/michinavatar.png',
    image: './visuals/Wrestlers/women/michin/michinfull.png',
    gender: 'Female',
    alignment: 'Face',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'RAW',
    holdsTitleNames: ['']
  },
  {
    name: 'Mistress Morrigan',
    avatar: './visuals/Wrestlers/women/mistressmorrigan/mistressmorriganavatar.png',
    image: './visuals/Wrestlers/women/mistressmorrigan/mistressmorriganfull.png',
    gender: 'Female',
    alignment: 'Heel',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'NXT',
    holdsTitleNames: ['']
  },
  {
    name: 'Naomi',
    avatar: './visuals/Wrestlers/women/naomi/naomiavatar.png',
    image: './visuals/Wrestlers/women/naomi/naomifull.png',
    gender: 'Female',
    alignment: 'Heel',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'SMACKDOWN',
    holdsTitleNames: ['']
  },
  {
    name: 'Natalya',
    avatar: './visuals/Wrestlers/women/natalya/natalyaavatar.png',
    image: './visuals/Wrestlers/women/natalya/natalyafull.png',
    gender: 'Female',
    alignment: 'Heel',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'RAW',
    holdsTitleNames: ['']
  },
  {
    name: 'Nia Jax',
    avatar: './visuals/Wrestlers/women/niajax/niajaxavatar.png',
    image: './visuals/Wrestlers/women/niajax/niajaxfull.png',
    gender: 'Female',
    alignment: 'Heel',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'SMACKDOWN',
    holdsTitleNames: ['']
  },
  {
    name: 'Nikki Bella',
    avatar: './visuals/Wrestlers/women/nikkibella/nikkibellaavatar.png',
    image: './visuals/Wrestlers/women/nikkibella/nikkibellafull.png',
    gender: 'Female',
    alignment: 'Face',
    faction: 'Bella Twins',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'RAW',
    holdsTitleNames: ['']
  },
  {
    name: 'Nikki Cross',
    avatar: './visuals/Wrestlers/women/nikkicross/nikkicrossavatar.png',
    image: './visuals/Wrestlers/women/nikkicross/nikkicrossfull.png',
    gender: 'Female',
    alignment: 'Heel',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'RAW',
    holdsTitleNames: ['']
  },
  {
    name: 'Piper Niven',
    avatar: './visuals/Wrestlers/women/piperniven/pipernivenavatar.png',
    image: './visuals/Wrestlers/women/piperniven/pipernivenfull.png',
    gender: 'Female',
    alignment: 'Heel',
    faction: 'ServiceHer',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'NXT',
    holdsTitleNames: ['']
  },
  {
    name: 'Raquel Rodriguez',
    avatar: './visuals/Wrestlers/women/raquelrodriguez/raquelrodriguezavatar.png',
    image: './visuals/Wrestlers/women/raquelrodriguez/raquelrodriguezfull.png',
    gender: 'Female',
    alignment: 'Heel',
    faction: 'Judgment Day',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'RAW',
    holdsTitleNames: ['']
  },
  {
    name: 'Rhea Ripley',
    avatar: './visuals/Wrestlers/women/rhearipley/rhearipleyavatar.png',
    image: './visuals/Wrestlers/women/rhearipley/rhearipleyfull.png',
    gender: 'Female',
    alignment: 'Face',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'SMACKDOWN',
    holdsTitleNames: ['']
  },
  {
    name: 'Roxanne Perez',
    avatar: './visuals/Wrestlers/women/roxanneperez/roxanneperezavatar.png',
    image: './visuals/Wrestlers/women/roxanneperez/roxanneperezfull.png',
    gender: 'Female',
    alignment: 'Face',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'RAW',
    holdsTitleNames: ['']
  },
  {
    name: 'Scarlett',
    avatar: './visuals/Wrestlers/women/scarlett/scarlettavatar.png',
    image: './visuals/Wrestlers/women/scarlett/scarlettfull.png',
    gender: 'Female',
    alignment: 'Heel',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'NXT',
    holdsTitleNames: ['']
  },
  {
    name: 'Shayna Baszler',
    avatar: './visuals/Wrestlers/women/shaynabaszler/shaynabaszleravatar.png',
    image: './visuals/Wrestlers/women/shaynabaszler/shaynabaszlerfull.png',
    gender: 'Female',
    alignment: 'Heel',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'SMACKDOWN',
    holdsTitleNames: ['']
  },
  {
    name: 'Shotzi',
    avatar: './visuals/Wrestlers/women/shotzi/shotziavatar.png',
    image: './visuals/Wrestlers/women/shotzi/shotzifull.png',
    gender: 'Female',
    alignment: 'Face',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'NXT',
    holdsTitleNames: ['']
  },
  {
    name: 'Sol Ruca',
    avatar: './visuals/Wrestlers/women/solruca/solrucaavatar.png',
    image: './visuals/Wrestlers/women/solruca/solrucafull.png',
    gender: 'Female',
    alignment: 'Face',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'SMACKDOWN',
    holdsTitleNames: ['']
  },
  {
    name: 'Sonya Deville',
    avatar: './visuals/Wrestlers/women/sonyadeville/sonyadevilleavatar.png',
    image: './visuals/Wrestlers/women/sonyadeville/sonyadevillefull.png',
    gender: 'Female',
    alignment: 'Heel',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'RAW',
    holdsTitleNames: ['']
  },
  {
    name: 'Stephanie Vaquer',
    avatar: './visuals/Wrestlers/women/stephanievaquer/stephanievaqueravatar.png',
    image: './visuals/Wrestlers/women/stephanievaquer/stephanievaquerfull.png',
    gender: 'Female',
    alignment: 'Face',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'RAW',
    holdsTitleNames: ['']
  },
  {
    name: 'Tamina',
    avatar: './visuals/Wrestlers/women/tamina/taminaavatar.png',
    image: './visuals/Wrestlers/women/tamina/taminafull.png',
    gender: 'Female',
    alignment: 'Heel',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'SMACKDOWN',
    holdsTitleNames: ['']
  },
  {
    name: 'Tatum Paxley',
    avatar: './visuals/Wrestlers/women/tatumpaxley/tatumpaxleyavatar.png',
    image: './visuals/Wrestlers/women/tatumpaxley/tatumpaxleyfull.png',
    gender: 'Female',
    alignment: 'Face',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'RAW',
    holdsTitleNames: ['']
  },
  {
    name: 'Tegan Nox',
    avatar: './visuals/Wrestlers/women/tegannox/tegannoxavatar.png',
    image: './visuals/Wrestlers/women/tegannox/tegannoxfull.png',
    gender: 'Female',
    alignment: 'Face',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'SMACKDOWN',
    holdsTitleNames: ['']
  },
  {
    name: 'Thea Hail',
    avatar: './visuals/Wrestlers/women/theahail/theahailavatar.png',
    image: './visuals/Wrestlers/women/theahail/theahailfull.png',
    gender: 'Female',
    alignment: 'Face',
    faction: 'Chase University',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'NXT',
    holdsTitleNames: ['']
  },
  {
    name: 'Tiffany Stratton',
    avatar: './visuals/Wrestlers/women/tiffanystratton/tiffanystrattonavatar.png',
    image: './visuals/Wrestlers/women/tiffanystratton/tiffanystrattonfull.png',
    gender: 'Female',
    alignment: 'Face',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'RAW',
    holdsTitleNames: ['']
  },
  {
    name: 'Valhalla',
    avatar: './visuals/Wrestlers/women/valhalla/valhallaavatar.png',
    image: './visuals/Wrestlers/women/valhalla/valhallafull.png',
    gender: 'Female',
    alignment: 'Heel',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'RAW',
    holdsTitleNames: ['']
  },
  {
    name: 'Wendy Choo',
    avatar: './visuals/Wrestlers/women/wendychoo/wendychooavatar.png',
    image: './visuals/Wrestlers/women/wendychoo/wendychoofull.png',
    gender: 'Female',
    alignment: 'Face',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'NXT',
    holdsTitleNames: ['']
  },
  {
    name: 'Zaria',
    avatar: './visuals/Wrestlers/women/zaria/zariaavatar.png',
    image: './visuals/Wrestlers/women/zaria/zariafull.png',
    gender: 'Female',
    alignment: 'Face',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'SMACKDOWN',
    holdsTitleNames: ['']
  },
  {
    name: 'Zelina Vega',
    avatar: './visuals/Wrestlers/women/zelinavega/zelinavegaavatar.png',
    image: './visuals/Wrestlers/women/zelinavega/zelinavegafull.png',
    gender: 'Female',
    alignment: 'Face',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'SMACKDOWN',
    holdsTitleNames: ['']
  },
  {
    name: 'Zoey Stark',
    avatar: './visuals/Wrestlers/women/zoeystark/zoeystarkavatar.png',
    image: './visuals/Wrestlers/women/zoeystark/zoeystarkfull.png',
    gender: 'Female',
    alignment: 'Heel',
    faction: '',
    rating: 0,
    wins: 0,
    losses: 0,
    draws: 0,
    injuryStatus: 'None',
    moral: 100,
    contract: 'Full-time',
    brandName: 'SMACKDOWN',
    holdsTitleNames: ['']
  }
];
